### ISSUE TITLE
Need to use Fitness Shaping for NES

### ISSUE THREAD

**Issue by Refefer** [ShangtongZhang/DistributedES#1]
Looking through the code, it doesn't appear you you've used fitness shaping to help mitigate early local minimas in your NES algo.  It's a fairly simple transform and Salimans et al. found it key to performance in their paper.

**Comment by ShangtongZhang** [comment]
Thanks for printing it out. I will look into the paper and fix it.

**Comment by ShangtongZhang** [comment]
Fixed, thanks again.
