### ISSUE TITLE
Making BipedalWalker learn

### ISSUE THREAD

**Issue by dhineshkumar-r** [ShangtongZhang/DistributedES#3]
Hi,
I ran experiments on natural_es.py for the BipedalWalker environment and I see that the learning curve is not consistent at all. Most of the time, the value saturates around -100. I tried different network architecture and activation units. I hardly see 1/2 of 5 runs actually learning. Did anyone face the such situation? The learning curves for other environments look as expected.
It would be helpful if someone could share some points/hints to make BipedalWalker-v2 learn.
Any help is appreciated.
Thanks

**Comment by ShangtongZhang** [comment]
Sorry I no longer maintain this project so can't provide any advice.
